# Shiny proxy configuration
proxy:
  title: Resilient Games
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-log-path: ./container-logs
  authentication: simple
  admin-groups: admins
  users:
    - name: gm
      password: ${SHINYPROXY_GM_PASS}
      groups: gms
    - name: player
      password: ${SHINYPROXY_PLAYER_PASS}
      groups: playas
    - name: admin
      password:  ${SHINYPROXY_ADMIN_PASS}
      groups: [gms, playas, admins]
  docker:
    internal-networking: true
    url: ${SHINYPROXY_DOCKER_PROXY}
    # url: http://localhost:2375
    #url: http://host.docker.internal:2375
    #url: unix:///var/run/docker.sock
    port-range-start: 20000
  specs:
  - id: controller_app
    display-name: Game Controller
    description: Application for managing the game details
    container-cmd: [
    "R", "-e", "resilientgames::run_one_app(\"controller\", \"/srv/resilient-games/output\")"
    ]
    container-image: resilientucsd/resilient-games-app
    container-network: resilient-proxy-net
    container-volumes:
      - resilient-games:/srv/resilient-games/output
    access-groups:
      - gms
  - id: newsfeed_app
    display-name: Newsfeed View
    description: Application for viewing in game newsfeed content
    container-cmd: [
    "R", "-e", "resilientgames::run_one_app(\"newsfeed\", \"/srv/resilient-games/output\")"
    ]
    container-image: resilientucsd/resilient-games-app
    container-network: resilient-proxy-net
    container-volumes:
      - resilient-games:/srv/resilient-games/output
    access-groups:
      - playas
  - id: status_app
    display-name: Status View
    description: Application for viewing game status updates
    container-cmd: [
    "R", "-e", "resilientgames::run_one_app(\"status\", \"/srv/resilient-games/output\")"
    ]
    container-image: resilientucsd/resilient-games-app
    container-network: resilient-proxy-net
    container-volumes:
      - resilient-games:/srv/resilient-games/output
    access-groups:
      - playas
  - id: player_app
    display-name: Player View
    description: Application for viewing newsfeed and status on one page
    container-cmd: [
    "R", "-e", "resilientgames::run_one_app(\"player\", \"/srv/resilient-games/output\")"
    ]
    container-image: resilientucsd/resilient-games-app
    container-network: resilient-proxy-net
    container-volumes:
      - resilient-games:/srv/resilient-games/output
    access-groups:
      - playas
logging:
  file:
    name: resilient-games.log
