version: "3.8"

# This allows read/write access in the container
#volumes:
#  logs:
#    driver: local
#    driver_opts:
#      type: none
#      device: ./shinyproxy-logs
#      o: bind
services:
  shinyproxy:
    image: resilientucsd/resilient-games-proxy
    container_name: resilient-proxy
    restart: on-failure
    build: ./proxy
    networks:
      - resilient-proxy-net
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/opt/shinyproxy/container-logs
      -  ./proxy/application.yml:/opt/shinyproxy/application.yml
    user: "shinyproxy:${DOCKERGRP:-docker}"

networks:
  resilient-proxy-net:
    name: resilient-proxy-net
