# This connects tcp:2375 to the docker socket to enable docker containers to
# talk to the docker daemon (allows spinning up new containers on the fly).
version: "3"
services:
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    user: root
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 2375:2375

  shinyproxy:
    extends:
      file: docker-compose.yml
      service: shinyproxy
    image: rishig32/resilient-proxy-osx
    build: none
    depends_on:
      - socat
