name: Dockerize Proxy Resilient  RShiny
on:
  push:
    branches:
      - main
      - dockerhub
# https://github.com/marketplace/actions/publish-docker
# https://github.com/docker/build-push-action
defaults:
  run:
    working-directory: .
jobs:
  deploy:
    name: Dockerize Games RShiny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Create Node Environment
        uses: actions/setup-node@v2
        env:
          NODE_ENV:
            production
        with:
          node-version: '14'
      - run: npm install
      #- run: npm install -g  yarn
      #- run: yarn install
      #- run: yarn build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: resilientucsd/resilient-games-proxy
          flavor: |
            latest=true
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: inst/serve/proxy/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #          tags: nsfearthcube/ec_facets_client:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
